### ISSUE TITLE
rosserial/serial permissions issue with ttyacm0

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain#169]
From @rwdavis513:

> After much debugging this weekend, the pfcs with the new software wouldn't be able to access the serial port anymore after 30-45minutes. Perhaps there was something that needs to change in the cmake or it needs to be run again. Here's a post with the error: http://answers.ros.org/question/233355/rosserial-running-please/

The error:

```
Traceback (most recent call last):
 File "/home/pi/catkin_ws/install/lib/rosserial_python/serial_node.py", line 80, in <module>
   client = SerialClient(port_name, baud)
 File "/home/pi/catkin_ws/install/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 382, in __init__
   self.requestTopics()
 File "/home/pi/catkin_ws/install/lib/python2.7/dist-packages/rosserial_python/SerialClient.py", line 389, in requestTopics
   self.port.flushInput()
 File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 500, in flushInput
   termios.tcflush(self.fd, TERMIOS.TCIFLUSH)
termios.error: (5, 'Input/output error')
```

Maybe related to https://github.com/OpenAgInitiative/openag_brain/issues/167?

**Comment by gordonbrander** [comment]
Some askubuntu threads on Arduino/serial port permissions.

https://askubuntu.com/questions/58119/changing-permissions-on-serial-port
https://askubuntu.com/questions/616517/dev-ttyacm0-permission-denied-error

**Comment by gordonbrander** [comment]
Should check the old install script to make sure that there isn't a chmod on the serial port at some point.

**Comment by gordonbrander** [comment]
From https://askubuntu.com/questions/616517/dev-ttyacm0-permission-denied-error

> add yourself to the dialout group, as described in thread you mentioned, then log out and back in. Now it should work. This is because the modification won't take effect until your current session is closed and a new one is started.
